// This file is auto-generated by Flutter tools to register web plugins.
// This file is required for the web platform to work correctly.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:moon_native/moon_native_web.dart';

void registerPlugins(Registrar registrar) {
  MoonNativeWeb.registerWith(registrar);
  registrar.registerMessageHandler();
}
